[general]
suspend_key = "F11"

[[keymap]]
name = "accessibility_core"

[keymap.mappings]
Super-a = "Ctrl-a"
Super-c = "Ctrl-c"
Super-s = "Ctrl-s"
Super-v = "Ctrl-v"
Super-x = "Ctrl-x"
Super-z = "Ctrl-z"

[[keymap]]
name = "accessibility_navigation"

[keymap.mappings]
Super-Backspace = "Ctrl-Backspace"
Super-Left = "Home"
Super-Right = "End"

[modmap.default]
CAPSLOCK = "CAPSLOCK"

[[multipurpose]]
hold = "RIGHT_CTRL"
name = "caps_to_esc_ctrl"
tap = "ESCAPE"
trigger = "CAPSLOCK"

[[multipurpose]]
hold = "RIGHT_CTRL"
name = "enter_to_ctrl"
tap = "ENTER"
trigger = "ENTER"

[timeouts]
multipurpose = 300
suspend = 1000
