# Mac Standard Profile - Fallback Keymaps
# Standard macOS-style Super key shortcuts

[[keymap]]
name = "mac_core_shortcuts"
condition = "not (wm_class =~ '(?i)jetbrains')"
[keymap.mappings]
"Super-a" = "Ctrl-a"
"Super-b" = "Ctrl-b"
"Super-c" = "Ctrl-c"
"Super-d" = "Ctrl-d"
"Super-e" = "Ctrl-e"
"Super-f" = "Ctrl-f"
"Super-g" = "Ctrl-g"
"Super-h" = "Ctrl-h"
"Super-i" = "Ctrl-i"
"Super-j" = "Ctrl-j"
"Super-k" = "Ctrl-k"
"Super-l" = "Ctrl-l"
"Super-m" = "Ctrl-m"
"Super-n" = "Ctrl-n"
"Super-o" = "Ctrl-o"
"Super-p" = "Ctrl-p"
"Super-q" = "Ctrl-q"
"Super-r" = "Ctrl-r"
"Super-s" = "Ctrl-s"
"Super-t" = "Ctrl-t"
"Super-u" = "Ctrl-u"
"Super-v" = "Ctrl-v"
"Super-w" = "Ctrl-w"
"Super-x" = "Ctrl-x"
"Super-y" = "Ctrl-y"
"Super-z" = "Ctrl-z"

[[keymap]]
name = "mac_navigation"
condition = "not (wm_class =~ '(?i)terminal|alacritty|kitty|wezterm|gnome-terminal|konsole|xfce4-terminal|ghostty|wave|terminology|deepin-terminal|contour|hyper|kgx|cosmicterm|blackbox')"
[keymap.mappings]
"Super-Left" = "Home"
"Super-Right" = "End"
"Super-Up" = "Ctrl-Home"
"Super-Down" = "Ctrl-End"
"Super-Backspace" = "Ctrl-Backspace"
"Super-Delete" = "Ctrl-Delete"
"Shift-Super-Left" = "Shift-Home"
"Shift-Super-Right" = "Shift-End"
