# Developer Profile - IDE and Terminal Optimized
# Mac-style base with developer-specific enhancements

[general]
suspend_key = "F11"

[timeouts]
multipurpose = 200
suspend = 1000

[modmap.default]
CAPSLOCK = "CAPSLOCK"

[[multipurpose]]
name = "caps_to_esc_ctrl"
trigger = "CAPSLOCK"
tap = "ESCAPE"
hold = "RIGHT_CTRL"

[[modmap.conditionals]]
name = "gui_ibm"
condition = "keyboard_type =~ 'IBM' and not (wm_class =~ '(?i)alacritty|blackbox|contour|cosmicterm|deepin-terminal|ghostty|gnome-terminal|hyper|kgx|kitty|konsole|terminology|wave|wezterm|xfce4-terminal')"
mappings = { CAPSLOCK = "LEFT_META", LEFT_CTRL = "LEFT_ALT", LEFT_ALT = "RIGHT_CTRL" }

[[modmap.conditionals]]
name = "terminals_ibm"
condition = "keyboard_type =~ 'IBM' and wm_class =~ '(?i)alacritty|blackbox|contour|cosmicterm|deepin-terminal|ghostty|gnome-terminal|hyper|kgx|kitty|konsole|terminology|wave|wezterm|xfce4-terminal'"
mappings = { CAPSLOCK = "LEFT_ALT", LEFT_ALT = "RIGHT_CTRL", RIGHT_CTRL = "RIGHT_ALT" }
