[general]
suspend_key = "F11"

[[keymap]]
condition = "wm_class =~ '(?i)terminal|alacritty|kitty|wezterm|gnome-terminal|konsole|xfce4-terminal|ghostty'"
name = "terminals_core_shortcuts"

[keymap.mappings]
Alt-Backspace = "Ctrl-w"
Alt-Delete = [
    "Esc",
    "d",
]
Super-Backspace = "Ctrl-u"
Super-Delete = "Ctrl-k"
Super-c = "Ctrl-Shift-c"
Super-d = "Ctrl-Shift-d"
Super-dot = "Ctrl-c"
Super-equal = "Ctrl-Shift-equal"
Super-f = "Ctrl-Shift-f"
Super-l = "Ctrl-Shift-l"
Super-minus = "Ctrl-minus"
Super-n = "Ctrl-Shift-n"
Super-s = "Ctrl-Shift-s"
Super-t = "Ctrl-Shift-t"
Super-v = "Ctrl-Shift-v"
Super-w = "Ctrl-Shift-w"

[[keymap]]
condition = "wm_class =~ '(?i)terminal|alacritty|kitty|konsole|ghostty|wave|terminology|deepin-terminal|contour|hyper'"
name = "terminals_general"

[keymap.mappings]
Alt-Delete = [
    "Esc",
    "d",
]

[[keymap]]
condition = "wm_class =~ '(?i)^alacritty$'"
name = "terminal_alacritty"

[keymap.mappings]
Super-k = "Ctrl-l"

[[keymap]]
condition = "wm_class =~ '(?i)^contour$'"
name = "terminal_contour"

[keymap.mappings]
Super-minus = "Ctrl-Shift-minus"

[[keymap]]
condition = "wm_class =~ '(?i)^com.system76.cosmicterm$'"
name = "terminal_cosmic"

[keymap.mappings]
Super-equal = "Ctrl-equal"

[[keymap]]
condition = "wm_class =~ '(?i)^deepin-terminal$'"
name = "terminal_deepin"

[keymap.mappings]
Super-equal = "Ctrl-equal"
Super-j = ["Ignore"]
Super-minus = "Ctrl-minus"
Super-w = "Alt-w"

[[keymap]]
condition = "wm_class =~ '(?i)ghostty'"
name = "terminal_ghostty"

[keymap.mappings]
Shift-Super-d = "Super-Shift-e"
Super-Alt-i = "Super-Shift-i"
Super-d = "Super-Shift-o"
Super-equal = "Ctrl-equal"
Super-k = "Ctrl-l"

[[keymap]]
condition = "wm_class =~ '(?i)^hyper$'"
name = "terminal_hyper"

[keymap.mappings]
Ctrl-Tab = [
    "bind",
    "Combo(Ctrl-Tab)",
]
Shift-Ctrl-Tab = [
    "bind",
    "Combo(Shift-Ctrl-Tab)",
]
Super-equal = "Ctrl-equal"

[[keymap]]
condition = "wm_class =~ '(?i)^kitty$'"
name = "terminal_kitty"

[keymap.mappings]
Super-k = "Ctrl-l"
Super-l = "Ctrl-l"

[[keymap]]
condition = "wm_class =~ '(?i)^konsole$|^org.kde.konsole$'"
name = "terminal_konsole"

[keymap.mappings]
Super-0 = "Ctrl-Alt-0"
Super-comma = "Shift-Ctrl-comma"
Super-k = "Shift-Ctrl-k"

[[keymap]]
condition = "wm_class =~ '(?i)^terminology$'"
name = "terminal_terminology"

[keymap.mappings]
Super-0 = "Ctrl-Alt-0"
Super-c = "Alt-w"
Super-equal = "Ctrl-Alt-equal"
Super-minus = "Ctrl-Alt-minus"
Super-v = "Alt-Enter"
Super-w = "Shift-Ctrl-End"

[[keymap]]
condition = "wm_class =~ '(?i)^wave$'"
name = "terminal_wave"

[keymap.mappings]
Shift-Super-n = "Shift-Alt-n"
Shift-Super-w = "Shift-Alt-w"
Super-n = "Alt-n"
Super-t = "Alt-t"
Super-w = "Alt-w"

[[keymap]]
condition = "wm_class =~ '(?i)^xfce4-terminal$'"
name = "terminal_xfce4"

[keymap.mappings]
Super-comma = [
    "Alt-e",
    "Delay(100)",
    "e",
]

[[keymap]]
condition = "wm_class =~ '(?i)com.raggesilver.blackbox|com.system76.cosmicterm|org.gnome.console|console|deepin-terminal|hyper|kitty|kgx'"
name = "terminal_tab_nav_ctrlshifttab"

[keymap.mappings]
Shift-Super-Left = "Ctrl-Shift-Tab"
Shift-Super-Left_Brace = "Ctrl-Shift-Tab"
Shift-Super-Page_Down = "Ctrl-Tab"
Shift-Super-Page_Up = "Ctrl-Shift-Tab"
Shift-Super-Right = "Ctrl-Tab"
Shift-Super-Right_Brace = "Ctrl-Tab"

[[keymap]]
condition = "wm_class =~ '(?i)^konsole$|^org.kde.konsole$'"
name = "terminal_konsole_tab_switching"

[keymap.mappings]
Ctrl-Grave = [
    "bind",
    "Combo(Shift-Left)",
]
Ctrl-Tab = [
    "bind",
    "Combo(Shift-Right)",
]
Shift-Ctrl-Tab = [
    "bind",
    "Combo(Shift-Left)",
]
Shift-Super-Left_Brace = [
    "bind",
    "Combo(Shift-Left)",
]
Shift-Super-Page_Down = [
    "bind",
    "Combo(Shift-Right)",
]
Shift-Super-Page_Up = [
    "bind",
    "Combo(Shift-Left)",
]
Shift-Super-Right_Brace = [
    "bind",
    "Combo(Shift-Right)",
]

[[keymap]]
condition = "wm_class =~ '(?i)^io.elementary.terminal$|^kitty$'"
name = "terminal_elementary_kitty_tab_switching"

[keymap.mappings]
Ctrl-Grave = [
    "bind",
    "Combo(Shift-Ctrl-Left)",
]
Ctrl-Tab = [
    "bind",
    "Combo(Shift-Ctrl-Right)",
]
Shift-Ctrl-Tab = [
    "bind",
    "Combo(Shift-Ctrl-Left)",
]

[[keymap]]
condition = "not (wm_class =~ 'code|code-oss|vscodium|cursor')"
name = "editors_wordwise_non_vscode"

[keymap.mappings]
Alt-Left = "Ctrl-Left"
Alt-Right = "Ctrl-Right"
Alt-Shift-Left = "Ctrl-Shift-Left"
Alt-Shift-Right = "Ctrl-Shift-Right"

[[keymap]]
condition = "wm_class =~ 'code|code-oss|vscodium|cursor'"
name = "editor_vscode_overrides"

[keymap.mappings]
Super-Grave = "Ctrl-Grave"
Super-c = "Ctrl-c"
Super-dot = "Ctrl-dot"
Super-f = "Ctrl-f"
Super-x = "Ctrl-x"

[[keymap]]
condition = "wm_class =~ '(?i)code|code-oss|vscodium|cursor'"
name = "editor_vscode_navigation"

[keymap.mappings]
Alt-Left = "Ctrl-Left"
Alt-Right = "Ctrl-Right"
Alt-Shift-Left = "Ctrl-Shift-Left"
Alt-Shift-Right = "Ctrl-Shift-Right"
Super-Backspace = [
    "Shift-Home",
    "Delete",
]
Super-Delete = [
    "Shift-End",
    "Delete",
]

[[keymap]]
condition = "wm_class =~ '(?i)jetbrains' and not (wm_class =~ '(?i)toolbox')"
name = "editor_jetbrains"

[keymap.mappings]
Alt-Backspace = "Ctrl-Backspace"
Alt-Delete = "Ctrl-Delete"
Alt-Down = "Ctrl-Shift-w"
Alt-Home = "Alt-Home"
Alt-Space = "Ctrl-Shift-i"
Alt-Up = "Ctrl-w"
Ctrl-Alt-o = "Ctrl-Alt-Shift-n"
Ctrl-Alt-r = "F9"
Ctrl-Backspace = "Ctrl-y"
Ctrl-Comma = "Ctrl-Alt-s"
Ctrl-Delete = "Alt-Delete"
Ctrl-Down = "Ctrl-Enter"
Ctrl-F3 = "Shift-F11"
Ctrl-Key_0 = "Alt-Key_0"
Ctrl-Key_1 = "Alt-Key_1"
Ctrl-Key_2 = "Alt-Key_2"
Ctrl-Key_3 = "Alt-Key_3"
Ctrl-Key_4 = "Alt-Key_4"
Ctrl-Key_5 = "Alt-Key_5"
Ctrl-Key_6 = "Alt-Key_6"
Ctrl-Key_7 = "Alt-Key_7"
Ctrl-Key_8 = "Alt-Key_8"
Ctrl-Key_9 = "Alt-Key_9"
Ctrl-Left_Brace = "Alt-Shift-Left"
Ctrl-Minus = "Ctrl-KPMINUS"
Ctrl-Right_Brace = "Alt-Shift-Right"
Ctrl-Semicolon = "Ctrl-Alt-Shift-s"
Ctrl-Shift-Equal = "Ctrl-Shift-KPPLUS"
Ctrl-Shift-F3 = "Shift-F3"
Ctrl-Shift-Minus = "Ctrl-Shift-KPMINUS"
Ctrl-Shift-o = "Ctrl-Shift-n"
Ctrl-Super-g = "Ctrl-Alt-Shift-j"
Ctrl-g = "F3"
Ctrl-l = "Ctrl-g"
Ctrl-n = "Alt-Insert"
Ctrl-o = "Ctrl-n"
Ctrl-t = "Ctrl-Alt-Shift-t"
Ctrl-w = "Ctrl-F4"
Ctrl-y = "Ctrl-Shift-i"
F2 = "F11"
Super-Alt-d = "Alt-Shift-F9"
Super-Alt-h = "Ctrl-Alt-h"
Super-Alt-i = "Ctrl-Alt-i"
Super-Alt-o = "Ctrl-Alt-o"
Super-Alt-r = "Alt-Shift-F10"
Super-Down = "Alt-Down"
Super-F3 = "Ctrl-F11"
Super-Grave = "Ctrl-Grave"
Super-Key_0 = "Ctrl-Key_0"
Super-Key_1 = "Ctrl-Key_1"
Super-Key_2 = "Ctrl-Key_2"
Super-Key_3 = "Ctrl-Key_3"
Super-Key_4 = "Ctrl-Key_4"
Super-Key_5 = "Ctrl-Key_5"
Super-Key_6 = "Ctrl-Key_6"
Super-Key_7 = "Ctrl-Key_7"
Super-Key_8 = "Ctrl-Key_8"
Super-Key_9 = "Ctrl-Key_9"
Super-Left = "Alt-Left"
Super-Right = "Alt-Right"
Super-Shift-b = "Ctrl-Shift-b"
Super-Shift-d = "Ctrl-Shift-F9"
Super-Shift-g = "Alt-Shift-j"
Super-Shift-j = "Ctrl-Shift-j"
Super-Shift-q = "Alt-q"
Super-Shift-r = "Ctrl-Shift-F10"
Super-Up = "Alt-Up"
Super-c = "Ctrl-c"
Super-d = "Shift-F9"
Super-g = "Alt-j"
Super-h = "Ctrl-h"
Super-i = "Ctrl-i"
Super-j = "Ctrl-q"
Super-o = "Ctrl-o"
Super-r = "Shift-F10"
Super-v = "Alt-Grave"

[[keymap]]
condition = "wm_class =~ '(?i)^org.kde.kate$'"
name = "editor_kate"

[keymap.mappings]
Super-Shift-g = "F3"
Super-comma = "Shift-Ctrl-comma"
Super-g = "Ctrl-g"

[[keymap]]
condition = "wm_class =~ '(?i)^kwrite$|^org.kde.kwrite$'"
name = "editor_kwrite"

[keymap.mappings]
Super-Alt-g = "Ctrl-g"
Super-Backspace = "Ctrl-k"
Super-Shift-g = "Shift-F3"
Super-comma = "Shift-Ctrl-comma"
Super-g = "F3"
Super-t = "Ctrl-n"

[[keymap]]
condition = "wm_class =~ '(?i)^kwrite$|^org.kde.kwrite$' and wm_name =~ '(?i)^Close Document.*KWrite$'"
name = "editor_kwrite_close_dialog"

[keymap.mappings]
Super-d = "Alt-d"
Super-s = "Alt-s"

[[keymap]]
condition = "wm_class =~ '(?i)^gedit$|^xed$'"
name = "editor_gedit_xed_tab_nav"

[keymap.mappings]
Shift-Super-Left_Brace = "Ctrl-Alt-Page_Up"
Shift-Super-Page_Down = "Ctrl-Alt-Page_Down"
Shift-Super-Page_Up = "Ctrl-Alt-Page_Up"
Shift-Super-Right_Brace = "Ctrl-Alt-Page_Down"

[[keymap]]
condition = "wm_class =~ '(?i)^xed$'"
name = "editor_xed"

[keymap.mappings]
Super-t = "Ctrl-n"

[[keymap]]
condition = "wm_class =~ '(?i)^gnome-text-editor$|^org.gnome.texteditor$'"
name = "editor_gnome_text_editor"

[keymap.mappings]
Super-Alt-f = "Ctrl-h"
Super-slash = ["Ignore"]

[[keymap]]
condition = "wm_class =~ '(?i)sublime'"
name = "editor_sublime"

[keymap.mappings]
Ctrl-Alt-v = [
    "Ctrl-k",
    "Ctrl-v",
]

[[keymap]]
condition = "wm_class =~ 'libreoffice-writer'"
name = "editor_libreoffice_writer"

[keymap.mappings]
Super-comma = "Alt-F12"

[[keymap]]
condition = "not (wm_class =~ '(?i)jetbrains')"
name = "dev_core_shortcuts"

[keymap.mappings]
Super-Backspace = "Ctrl-Backspace"
Super-Delete = "Ctrl-Delete"
Super-Left = "Home"
Super-Right = "End"
Super-a = "Ctrl-a"
Super-c = "Ctrl-c"
Super-d = "Ctrl-d"
Super-f = "Ctrl-f"
Super-g = "Ctrl-g"
Super-h = "Ctrl-h"
Super-k = "Ctrl-k"
Super-n = "Ctrl-n"
Super-o = "Ctrl-o"
Super-p = "Ctrl-p"
Super-r = "Ctrl-r"
Super-s = "Ctrl-s"
Super-t = "Ctrl-t"
Super-v = "Ctrl-v"
Super-w = "Ctrl-w"
Super-x = "Ctrl-x"
Super-y = "Ctrl-y"
Super-z = "Ctrl-z"

[[modmap.conditionals]]
condition = "keyboard_type =~ 'IBM' and not (wm_class =~ '(?i)alacritty|blackbox|contour|cosmicterm|deepin-terminal|ghostty|gnome-terminal|hyper|kgx|kitty|konsole|terminology|wave|wezterm|xfce4-terminal')"
name = "gui_ibm"

[modmap.conditionals.mappings]
CAPSLOCK = "LEFT_META"
LEFT_ALT = "RIGHT_CTRL"
LEFT_CTRL = "LEFT_ALT"

[[modmap.conditionals]]
condition = "keyboard_type =~ 'IBM' and wm_class =~ '(?i)alacritty|blackbox|contour|cosmicterm|deepin-terminal|ghostty|gnome-terminal|hyper|kgx|kitty|konsole|terminology|wave|wezterm|xfce4-terminal'"
name = "terminals_ibm"

[modmap.conditionals.mappings]
CAPSLOCK = "LEFT_ALT"
LEFT_ALT = "RIGHT_CTRL"
RIGHT_CTRL = "RIGHT_ALT"

[modmap.default]
CAPSLOCK = "CAPSLOCK"

[[multipurpose]]
hold = "RIGHT_CTRL"
name = "caps_to_esc_ctrl"
tap = "ESCAPE"
trigger = "CAPSLOCK"

[timeouts]
multipurpose = 200
suspend = 1000
